spring:
  application:
    decrireAction: urgents

  # Database configuration
  datasource:
    url : jdbc:mariadb://localhost:3306/gestion_cas?createDatabaseIfNotExist=true
    username : root
    password : root

  jpa:
    hibernate:
      ddl-auto : update
      properties:
        hibernate:
          dialect : org.hibernate.spatial.dialect.mysql.MySQL56SpatialDialect # utile pour la configuration de geometry
# l'image par défaut
app:
  image-path-prefix: http://${server.hostname}:${server.port}/gestiondecas/images/
  default-image-name: jpeg.jpg

 # Choisir une enumeration pardéfaut
  jackson:
    deserialization:
      read-unknown-enum-values-using-default-value : true

  #devtools:
    #restart:
      #enabled: false

# JWT Configuration
jwt:
  secret : ${SECRETE_KEY}
  expiration : 3600000

server:
  hostname: ${ hostname }
  port : 8081
  address: 0.0.0.0
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: always
