spring:
  profiles:
    active: local
  application:
    decrireAction: urgents

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update

---
spring:
  config:
    activate:
      on-profile: railway
  datasource:
    url: jdbc:${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
---
spring:
  jpa:
    hibernate:
      ddl-auto : update
# l'image par défaut
#app:
#  image-path-prefix: http://${server.hostname}:${server.port}/gestiondecas/images/
#  default-image-name: jpeg.jpg

 # Choisir une enumeration pardéfaut
  jackson:
    deserialization:
      read-unknown-enum-values-using-default-value : true

  #devtools:
    #restart:
      #enabled: false

# JWT Configuration
jwt:
  secret : ${SECRET_KEY}
  expiration : 36000000

# Pour l'API chinguitel
chingui:
  validationKey: ${VALIDATION_KEY}
  validationToken: ${VALIDATION-TOKEN}

server:
  port : ${PORT:8080}
  address: 0.0.0.0
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: on_param
