spring:
  application:
    decrireAction: urgents

  # Database configuration
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto : update
      properties:
        hibernate:
          dialect : org.hibernate.spatial.dialect.mysql.MySQL56SpatialDialect # utile pour la configuration de geometry
# l'image par défaut
app:
  image-path-prefix: http://${server.hostname}:${server.port}/gestiondecas/images/
  default-image-name: jpeg.jpg

 # Choisir une enumeration pardéfaut
  jackson:
    deserialization:
      read-unknown-enum-values-using-default-value : true

  #devtools:
    #restart:
      #enabled: false

# JWT Configuration
jwt:
  secret : ${SECRET_KEY}
  expiration : 36000000

# Pour l’API publique
sms:
  api:
    url : https://textbelt.com/text
    key : textbelt
# Pour verifier le numéro de l'utilisateur via otp
twilio:
  account-sid: ${TWILIO_ACCOUNT_SID}
  auth-token: ${TWILIO_AUTH_TOKEN}
  phone-number: ${TWILIO_PHONE_NUMBER}

server:
  hostname: ${SERVER_HOST_NAME}
  port : ${PORT:8080}
  address: 0.0.0.0
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: always
